# .github/workflows/lint-pr.yml
name: Lint Assignment
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.changed-files-mdlint.outputs.any_changed }}
      changed_files_mdlint: ${{ steps.changed-files-mdlint.outputs.all_changed_files }}
      changed_files_vale: ${{ steps.changed-files-vale.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Get changed markdown file list for vale
        id: changed-files-vale
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **/*.md
          separator: ','

      - name: Get changed markdown file list for markdownlint
        id: changed-files-mdlint
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **/*.md

  markdownlint:
    needs: get-changed-files
    if: needs.get-changed-files.outputs.any_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run markdownlint
        uses: nosborn/github-action-markdown-cli@v3
        with:
          files: ${{ needs.get-changed-files.outputs.changed_files_mdlint }}
          config_file: .markdownlint.json
  
  vale:
    needs: get-changed-files
    if: needs.get-changed-files.outputs.any_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
     
      - name: Install Vale
        run: |
          wget https://github.com/errata-ai/vale/releases/download/v3.12.0/vale_3.12.0_Linux_64-bit.tar.gz
          tar -xvzf vale_3.12.0_Linux_64-bit.tar.gz
          sudo mv vale /usr/local/bin/
          vale --version

      - name: Show Vale config
        run: |
          vale ls-config

      - name: Run Vale
        uses: errata-ai/vale-action@v2.1.1
        with:
          version: '3.12.0'
          files: ${{ needs.get-changed-files.outputs.changed_files_vale }}
          separator: ' '
          # assumes that config: .vale.ini
          fail_on_error: true
        # run: |
        #   vale --config=.vale.ini --minAlertLevel=suggestion ${{ needs.get-changed-files.outputs.changed_files }}
